# Generated by Django 5.2.13 on 2026-04-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessmembership',
            options={'ordering': ('business_id', 'user_id')},
        ),
    ]
