# Generated by Django 5.2.13 on 2026-04-21 15:11

import datetime
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('ai_settings', models.JSONField(blank=True, default=dict, help_text='System prompt, model name, temperature and tool settings.')),
                ('knowledge_base', models.TextField(blank=True, help_text='Business-specific context for the AI assistant.')),
                ('timezone_name', models.CharField(default='Asia/Almaty', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'businesses',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ')),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_failure_count', models.PositiveSmallIntegerField(default=0)),
                ('allow_follow_up', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='bookings.business')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('name', 'phone'),
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='bookings.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='bookings.client')),
            ],
            options={
                'verbose_name': 'conversation message',
                'verbose_name_plural': 'conversation messages',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text="Weekly schedule by weekday, for example {'mon': {'start': '09:00', 'end': '18:00'}}.")),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='bookings.business')),
            ],
            options={
                'verbose_name': 'master',
                'verbose_name_plural': 'masters',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duration', models.DurationField()),
                ('buffer_time', models.DurationField(default=datetime.timedelta(0))),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bookings.business')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_duration', models.DurationField(blank=True, editable=False, null=True)),
                ('service_buffer_time', models.DurationField(blank=True, editable=False, null=True)),
                ('client_data', models.JSONField(blank=True, default=dict)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('no_show', 'No show'), ('needs_attention', 'Needs attention')], default='pending', max_length=20)),
                ('follow_up_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.client')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.service')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ('start_time',),
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('business', 'phone'), name='uniq_client_phone_per_business'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['business', 'client', 'channel', 'created_at'], name='bookings_co_busines_318fbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='master',
            constraint=models.UniqueConstraint(fields=('business', 'full_name'), name='uniq_master_name_per_business'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='uniq_service_name_per_business'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gt', datetime.timedelta(0))), name='service_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('buffer_time__gte', datetime.timedelta(0))), name='service_buffer_time_non_negative'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['business', 'start_time'], name='bookings_bo_busines_8aa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['master', 'start_time', 'status'], name='bookings_bo_master__32f52d_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_end_after_start'),
        ),
    ]
