# Generated by Django 5.2.13 on 2026-04-22 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=32)),
                ('message_type', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='bookings.booking')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='bookings.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='bookings.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=32)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_events', to='bookings.business')),
            ],
            options={
                'ordering': ('-received_at',),
                'constraints': [models.UniqueConstraint(fields=('business', 'channel', 'provider_event_id'), name='uniq_inbound_event')],
            },
        ),
    ]
