# Generated by Django 5.2.13 on 2026-04-22 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_outboundmessage_inboundevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundmessage',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='bookings.client'),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=32),
        ),
    ]
