# Generated by Django 5.2.13 on 2026-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_outboundmessage_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='dead_lettered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], default='queued', max_length=32),
        ),
    ]
