# Generated by Django 5.2.13 on 2026-04-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_outboundmessage_dead_lettered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('system', 'System'), ('ai', 'AI'), ('human', 'Human'), ('provider', 'Provider')], default='system', max_length=20)),
                ('event_type', models.CharField(max_length=64)),
                ('channel', models.CharField(blank=True, default='', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='bookings.booking')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bookings.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='bookings.client')),
                ('outbound_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='bookings.outboundmessage')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business', 'event_type', 'created_at'], name='bookings_au_busines_df9fa3_idx'), models.Index(fields=['outbound_message', 'created_at'], name='bookings_au_outboun_0f2ba1_idx'), models.Index(fields=['booking', 'created_at'], name='bookings_au_booking_01d321_idx')],
            },
        ),
    ]
