# Generated by Django 5.2.13 on 2026-04-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(default='Алматы', max_length=120),
        ),
        migrations.AddField(
            model_name='business',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_messages', models.JSONField(blank=True, default=list)),
                ('response_text', models.TextField(blank=True)),
                ('summary_text', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interaction_logs', to='bookings.business')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business', 'created_at'], name='bookings_ai_busines_afd595_idx'), models.Index(fields=['status', 'created_at'], name='bookings_ai_status_6daab7_idx')],
            },
        ),
    ]
