# Generated by Django 5.2.13 on 2026-04-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_business_address_business_brand_name_business_city_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['booking', 'message_type', 'status'], name='bookings_ou_booking_50e6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['status', 'created_at'], name='bookings_ou_status_a7efe0_idx'),
        ),
    ]
