# Generated by Django 5.2.13 on 2026-04-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_business_ai_rules_category_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('dead_letter', 'Dead letter')], default='queued', max_length=32),
        ),
    ]
