# Generated by Django 5.2.13 on 2026-04-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_outboundmessage_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='outboundmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False), ('message_type__in', ('reminder', 'follow_up'))), fields=('booking', 'message_type'), name='uniq_booking_scheduled_outbound'),
        ),
    ]
