# Generated by Django 5.2.13 on 2026-05-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_outboundmessage_uniq_booking_scheduled_outbound"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp")],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("awaiting_date", "Awaiting date"),
                            ("awaiting_slot_choice", "Awaiting slot choice"),
                            ("awaiting_confirmation", "Awaiting confirmation"),
                        ],
                        default="idle",
                        max_length=32,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("selected_start_time", models.DateTimeField(blank=True, null=True)),
                ("selected_end_time", models.DateTimeField(blank=True, null=True)),
                ("slot_options", models.JSONField(blank=True, default=list)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_sessions",
                        to="bookings.business",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_sessions",
                        to="bookings.client",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_sessions",
                        to="bookings.master",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_sessions",
                        to="bookings.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking session",
                "verbose_name_plural": "booking sessions",
                "ordering": ("business_id", "client_id", "channel"),
            },
        ),
        migrations.AddConstraint(
            model_name="bookingsession",
            constraint=models.UniqueConstraint(
                fields=("business", "client", "channel"),
                name="uniq_booking_session_per_client_channel",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingsession",
            index=models.Index(fields=["expires_at"], name="bookings_bo_expires_68ec94_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingsession",
            index=models.Index(
                fields=["business", "client", "channel", "state"],
                name="bookings_bo_busines_3bf014_idx",
            ),
        ),
    ]
