# Generated by Django 5.2.13 on 2026-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_conversationthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cancellation_policy_hours',
            field=models.PositiveSmallIntegerField(default=2, help_text='Минимальный запас часов до начала записи, при котором клиент может отменить её через бота. Если до записи остаётся меньше этого порога — бот эскалирует запрос на администратора. 0 = разрешать отмену в любое время.'),
        ),
    ]
