# Generated by Django 5.2.13 on 2026-05-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_business_cancellation_policy_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsession',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('awaiting_date', 'Awaiting date'), ('awaiting_slot_choice', 'Awaiting slot choice'), ('awaiting_confirmation', 'Awaiting confirmation'), ('cancel_choosing', 'Cancellation: choosing booking'), ('cancel_confirming', 'Cancellation: confirming booking')], default='idle', max_length=32),
        ),
    ]
