# Generated by Django 5.2.13 on 2026-05-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_bookingsession_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteractionlog',
            name='completion_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='prompt_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
