# Generated by Django 5.2.13 on 2026-05-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_bookingsession_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='day_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
