# Generated by Django 5.2.13 on 2026-05-15 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_booking_day_reminder_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_unavailabilities', to='bookings.business')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='bookings.master')),
            ],
            options={
                'verbose_name': 'master unavailability',
                'verbose_name_plural': 'master unavailabilities',
                'ordering': ('start_time', 'master__full_name'),
                'indexes': [models.Index(fields=['business', 'start_time', 'end_time'], name='bookings_ma_busines_f5c16d_idx'), models.Index(fields=['master', 'start_time', 'end_time'], name='bookings_ma_master__e2f50b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='master_unavailability_end_after_start')],
            },
        ),
    ]
