# Generated by Django 5.2.13 on 2026-05-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_masterunavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='green_api_api_token',
            field=models.CharField(blank=True, default='', help_text='API-токен для Green-API instance. Plaintext в БД (тех-долг — шифрование после деплоя).', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='green_api_api_url',
            field=models.CharField(blank=True, default='', help_text='Опциональный override базового URL Green-API (например, https://api.green-api.com). Пусто = settings.GREEN_API_URL.', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='green_api_instance_id',
            field=models.CharField(blank=True, default='', help_text="Green-API instance id (idInstance). Используется для маршрутизации входящих webhook'ов и отправки исходящих сообщений именно с этого WhatsApp-аккаунта. Пусто = откатиться на глобальные GREEN_API_* из env (deprecated).", max_length=64),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(condition=models.Q(('green_api_instance_id', ''), _negated=True), fields=('green_api_instance_id',), name='uniq_business_green_api_instance_id'),
        ),
    ]
