# Generated by Django 5.2.13 on 2026-05-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_business_green_api_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Per-business Telegram bot token (из BotFather). Используется для отправки исходящих сообщений именно с этого бота. Пусто = откатиться на глобальный settings.TELEGRAM_BOT_TOKEN (deprecated). Plaintext в БД (тех-долг — шифрование вместе с green_api_api_token после деплоя).', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='telegram_webhook_secret',
            field=models.CharField(blank=True, default='', help_text="Per-business secret для входящих Telegram webhook'ов. URL /api/v1/webhooks/telegram/<business_id>/<secret>/ принимается только если пара (id, secret) совпадает с этой записью. Пусто = откатиться на settings.TELEGRAM_WEBHOOK_SECRET (deprecated).", max_length=128),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_webhook_secret', ''), _negated=True), fields=('telegram_webhook_secret',), name='uniq_business_telegram_webhook_secret'),
        ),
    ]
