# Generated by Django 5.2.13 on 2026-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_business_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('start_time',), 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='bookingsession',
            options={'ordering': ('business_id', 'client_id', 'channel'), 'verbose_name': 'Сессия бронирования', 'verbose_name_plural': 'Сессии бронирования'},
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ('name',), 'verbose_name': 'Салон', 'verbose_name_plural': 'Салоны'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name', 'phone'), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'Сообщение в диалоге', 'verbose_name_plural': 'Сообщения в диалогах'},
        ),
        migrations.AlterModelOptions(
            name='conversationthread',
            options={'ordering': ('business_id', 'client_id', 'channel'), 'verbose_name': 'Диалог', 'verbose_name_plural': 'Диалоги'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ('full_name',), 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='masterunavailability',
            options={'ordering': ('start_time', 'master__full_name'), 'verbose_name': 'Отсутствие мастера', 'verbose_name_plural': 'Отсутствия мастеров'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтверждена'), ('pending', 'Ожидает'), ('cancelled', 'Отменена'), ('no_show', 'Неявка'), ('needs_attention', 'Нужна проверка')], default='pending', max_length=20),
        ),
    ]
